export const actionTypes = {
    DELETE_TASK: 'DELETE_TASK',
    ADD_TASK: 'ADD_TASK',
    TOGGLE_TASK: 'TOGGLE_TASK',
    SET_FILTER: 'SET_FILTER',
    SHOW_ACTIVE: 'SHOW_ACTIVE',
    SHOW_READY: 'SHOW_READY',
    SHOW_ALL: 'SHOW_ALL'
}